export { default as Login } from './Login/Login'
export { default as Registration } from './Registration/Registration'
export { default as Dialogs } from './Dialogs/Dialogs'
export { default as Chat } from './Chat/Chat'
export { default as Profile } from './Profile/Profile'
